version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # 주의 할 점은 빈칸 yml파일 특성상 빈칸 개수를 중시해야하고 Tab을 쓰면 안된다는점
  # AfterInstall앞은 2칸이다.
  AfterInstall:
    # location은 프로젝트 기준으로 위치를 작성해준다!
    - location: start.sh
      # runas를 입력해주지 않으면 간혹 permission error가 날 수도
      runas: ec2-user