version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # 주의 할 점은 빈칸 yml파일 특성상 빈칸 개수를 중시해야하고 Tab을 쓰면 안된다는점
  # AfterInstall앞은 2칸이다.
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user