spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://gajoa-db.cklyw6tgbrhb.ap-northeast-2.rds.amazonaws.com:3306/gajoa_test_db
    username: xxxx
    password: xxxxxxxx
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
