spring:
  #  profiles: dev
  profiles: local
  datasource:
    url: jdbc:mariadb://gajoa-db1.cklyw6tgbrhb.ap-northeast-2.rds.amazonaws.com:3306/gajoa_test_db1
    username: admin
    password: rkdalsrb12#
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
